const SESSION_ID = "SADIYA-MD=7ow1ALSC#AkLCPLjN2GYPmiV3QN87Ew-RyAJ_mWRnRdEP7KqyjBY"
const BOT_NUMBER = "94715494635"
const GITHUB_AUTH_TOKEN = "loocg9MihnFZMKp3QhD7aqXoTbpMtK09sExF"

module.exports = {SESSION_ID,BOT_NUMBER,GITHUB_AUTH_TOKEN}
